# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-26 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coppia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lui', models.TextField(default=b'')),
                ('lei', models.TextField(default=b'')),
                ('comune', models.TextField(default=b'')),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Greeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True, verbose_name=b'date created')),
            ],
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('edition', models.IntegerField(default=0)),
                ('type', models.TextField(default=b'')),
                ('date', models.TextField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img_src', models.TextField(default=b'#')),
                ('id_magazine', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='hello.Magazine')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('username', models.TextField(default=b'')),
                ('RSAname', models.TextField(default=b'')),
                ('RSAlocation', models.TextField(default=b'')),
                ('RSAmagazine', models.TextField(default=b'')),
            ],
        ),
        migrations.AddField(
            model_name='magazine',
            name='id_user',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='hello.User'),
        ),
    ]
