# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
    ]
