# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-26 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='magazine',
            old_name='id_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='id_magazine',
            new_name='magazine',
        ),
    ]
