# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-02 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_photo_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='tags',
            field=models.TextField(default=b''),
        ),
    ]
