# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-28 09:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20160426_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magazine_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.TextField(default=b'')),
            ],
        ),
        migrations.RemoveField(
            model_name='magazine',
            name='type',
        ),
        migrations.AddField(
            model_name='user',
            name='img_src',
            field=models.TextField(default=b''),
        ),
        migrations.AlterField(
            model_name='photo',
            name='magazine',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='hello.Magazine_type'),
        ),
        migrations.AddField(
            model_name='magazine_type',
            name='id_magazine',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='hello.Magazine'),
        ),
    ]
