# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 11:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_utente'),
    ]

    operations = [
        migrations.AddField(
            model_name='utente',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='utente',
            name='email',
            field=models.TextField(default=b'null@null.it'),
        ),
        migrations.AddField(
            model_name='utente',
            name='name',
            field=models.TextField(default=b'null'),
        ),
    ]
