# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-04 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_photo_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(default=b'')),
                ('tags', models.TextField(default=b'')),
                ('instruction', models.TextField(default=b'')),
                ('rsa', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='hello.User')),
            ],
        ),
        migrations.CreateModel(
            name='Relative',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('username', models.TextField(default=b'')),
                ('full_name', models.TextField(default=b'')),
                ('rsa', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='hello.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='magazinetype',
            name='type',
        ),
        migrations.AddField(
            model_name='magazinetype',
            name='category',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='hello.Category'),
        ),
    ]
