# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-28 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20160428_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='img_src',
        ),
        migrations.AddField(
            model_name='photo',
            name='id_creator',
            field=models.TextField(default=b''),
        ),
        migrations.AddField(
            model_name='photo',
            name='img_src_creator',
            field=models.TextField(default=b''),
        ),
        migrations.AddField(
            model_name='photo',
            name='username_creator',
            field=models.TextField(default=b''),
        ),
    ]
