# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20160218_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('date', models.TextField(default=django.utils.timezone.now)),
                ('message', models.TextField(default=b'null')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField(default=b'null')),
                ('gender', models.TextField(default=b'null')),
                ('email', models.TextField(default=b'null@null.it')),
                ('birthday', models.TextField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Utente',
        ),
    ]
