# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_auto_20160219_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='date',
            new_name='created_time',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='message',
        ),
        migrations.AddField(
            model_name='photo',
            name='name',
            field=models.TextField(default=b''),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.TextField(default=b''),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.TextField(default=b''),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.TextField(default=b''),
        ),
    ]
