# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_auto_20160220_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='hello.User')),
            ],
        ),
    ]
