# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='id_user',
        ),
        migrations.AddField(
            model_name='friend',
            name='friend',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='friend', to='hello.User'),
        ),
        migrations.AddField(
            model_name='friend',
            name='user',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='hello.User'),
        ),
    ]
