# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0009_auto_20160220_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id_post', models.TextField(primary_key=True, serialize=False)),
                ('date', models.TextField(default=django.utils.timezone.now)),
                ('story', models.TextField(default=b'')),
                ('description', models.TextField(default=b'')),
                ('type', models.TextField(default=b'')),
                ('id_creator', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='id_creator', to='hello.User')),
                ('to', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='to', to='hello.User')),
            ],
        ),
    ]
