# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-04 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0010_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coppia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lui', models.TextField(default=b'')),
                ('lei', models.TextField(default=b'')),
                ('comune', models.TextField(default=b'')),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
