# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-28 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeshare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='type',
            field=models.TextField(default=b''),
        ),
    ]
